// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: ``
//     Provider:               ``
//     Connection String:      ``
//     Include Views:          `True`


// -----------------------------------------------------------------------------------------
// Failed to load provider `` - Value cannot be null. Parameter name: providerInvariantName
// -----------------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RestfulGeoCoder.Models
{
}
